### ISSUE TITLE
Failing of Scrapping  of the profile  page

### ISSUE THREAD

**Issue by Sarath191181208** [CSI-VIT-AP/VITask#1]
> **Relative  path** :  .\VITask Web\vtop.py
> **line:** 223
> **branch:** VIT-AP

---

## Part of  code potential error

- Profile  end point `PROFILE = r"https://vtop2.vitap.ac.in/vtop/studentsRecord/StudentProfileAllView"`
- Request  in network tab : Redirect  to -> https://vtop2.vitap.ac.in/vtop/studentsRecord/StudentProfileAllView 
![image](https://user-images.githubusercontent.com/74459981/162861271-3ce9af27-ba31-4866-a7c4-4a57452b28fa.png)

### Code Snippet

```python3
    try:
        profile_sess = sess.post(PROFILE, data=payload, headers=HEADERS, verify=False)
        # Check for 200 CODE
        if profile_sess.status_code !=200:
            status = False
    except:
        status = False
    finally:
        profile_html = profile_sess.text
        with open('profile_scrape.html', 'w') as  f:
            f.write(profile_html)
        try:
            profile = parse_profile(profile_html)

```

## Response HTML
```HTML
Session Timed out
You are logged out due to inactivity for more than 15 minutes
Login to VTOP
```

## Manual API call
![image](https://user-images.githubusercontent.com/74459981/162862492-c64eb262-c3a3-4d05-a82a-d0b854219572.png)

**Comment by apratimshukla6** [comment]
The issue is primarily due to incorrectly defined constants, and a modification that is needed for the username (which should be the register number). I'm adding a sample file called try.py so that you can get an idea of what I mean by that, make sure to configure it properly with a firebase.json and corresponding URLs. I have tested this file and it's working properly to extract the profile contents.

![Screenshot_11](https://user-images.githubusercontent.com/16684262/167524912-0ffa6cab-8070-4a05-8aca-5ea62fbdc9a0.png)

Note: You still need to modify the parsing logic to meet your needs, so make sure to experiment with individual functions and corresponding parsing with try.py
